# Generated by Django 4.0.6 on 2022-07-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='teamleader',
            options={'ordering': ['username'], 'verbose_name': 'Тим-лидер', 'verbose_name_plural': 'Тим-лидеры'},
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ManyToManyField(related_name='office_location', to='clientapp.office'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='clientapp.teamleader'),
        ),
    ]
