# Generated by Django 4.0.6 on 2022-07-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_alter_user_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='clientapp.teamleader'),
        ),
    ]
