# Generated by Django 4.0.6 on 2022-07-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_alter_user_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_leader',
            new_name='teamleader',
        ),
    ]
