# Generated by Django 4.0.6 on 2022-07-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_rename_team_leader_user_teamleader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teamleader',
        ),
        migrations.AddField(
            model_name='office',
            name='teamleader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='clientapp.teamleader'),
        ),
    ]
