# Generated by Django 4.0.6 on 2022-07-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_remove_user_teamleader_office_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teamleader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.teamleader'),
        ),
    ]
